export const VARIABLE_LABELS = {
  ai_disclosure: "AI 관련 공시 여부",
  ai_disclosure_rate: "AI 관련 공시 비율",
  ai_sentence_count: "AI 관련 문장 수",
  log1p_ai_sentence_count: "로그 AI 관련 문장 수",
  mean_ai_sentence_count_all: "AI 관련 문장 수(전체 평균)",
  mean_ai_sentence_count_disclosers: "AI 관련 공시 기업의 AI 관련 문장 평균",
  whole_report_concreteness: "전체 보고서 구체성",
  mean_whole_report_concreteness_all: "전체 보고서 구체성",
  ai_concreteness: "AI 관련 문장 구체성",
  mean_ai_concreteness_disclosers: "AI 관련 문장 구체성",
  past_tense_share: "과거 시제 비율",
  present_tense_share: "현재 시제 비율",
  future_tense_share: "미래 조동사 표지 비율",
  lm_positive_share: "Loughran–McDonald 긍정 어휘 비율",
  lm_negative_share: "Loughran–McDonald 부정 어휘 비율",
  lm_uncertainty_share: "Loughran–McDonald 불확실성 어휘 비율",
  ai_lm_positive_share: "AI 관련 문장의 Loughran–McDonald 긍정 어휘 비율",
  ai_lm_negative_share: "AI 관련 문장의 Loughran–McDonald 부정 어휘 비율",
  ai_lm_uncertainty_share: "AI 관련 문장의 Loughran–McDonald 불확실성 어휘 비율",
  passive_voice_sentence_share: "수동태 문장 비율",
  fog_index: "Fog Index",
  report_word_count: "보고서 단어 수",
  mean_report_word_count_all: "평균 보고서 단어 수",
  log_report_word_count: "로그 보고서 단어 수",
};

export const VARIABLE_UNITS = {
  ai_disclosure: "%",
  ai_disclosure_rate: "%",
  ai_sentence_count: "개",
  log1p_ai_sentence_count: "로그값",
  mean_ai_sentence_count_all: "개",
  mean_ai_sentence_count_disclosers: "개",
  whole_report_concreteness: "점",
  mean_whole_report_concreteness_all: "점",
  ai_concreteness: "점",
  mean_ai_concreteness_disclosers: "점",
  past_tense_share: "%",
  present_tense_share: "%",
  future_tense_share: "%",
  lm_positive_share: "%",
  lm_negative_share: "%",
  lm_uncertainty_share: "%",
  ai_lm_positive_share: "%",
  ai_lm_negative_share: "%",
  ai_lm_uncertainty_share: "%",
  passive_voice_sentence_share: "%",
  fog_index: "지수",
  report_word_count: "단어",
  mean_report_word_count_all: "단어",
  log_report_word_count: "로그값",
};

export const RESEARCH_VARIABLES = [
  "ai_disclosure",
  "ai_sentence_count",
  "log1p_ai_sentence_count",
  "whole_report_concreteness",
  "ai_concreteness",
  "past_tense_share",
  "present_tense_share",
  "future_tense_share",
  "lm_positive_share",
  "lm_negative_share",
  "lm_uncertainty_share",
  "passive_voice_sentence_share",
  "fog_index",
  "report_word_count",
  "log_report_word_count",
];

export const PUBLIC_VARIABLE_DEFINITIONS = {
  ai_disclosure: {
    concept: "10-K에 AI 관련 공시가 나타났는지를 나타내는 이진 변수이다.",
    operation: "정제된 본문에서 비중복 AI 관련 문장이 한 개 이상이면 1, 없으면 0으로 기록한다.",
    formula: "AI 관련 공시 여부ᵢₜ = 1(AI 관련 문장 수ᵢₜ ≥ 1)",
    numerator: "AI 관련 문장 1개 이상 여부",
    denominator: "해당 없음",
    unit: "0 또는 1",
    sample: "2020–2025년 전체 기업-연도",
    missingZero: "자료가 없으면 결측이며, 적격 문장이 없으면 0이다.",
  },
  ai_sentence_count: {
    concept: "10-K에서 관찰된 AI 관련 공시의 문장 수준 빈도이다.",
    operation: "AI 관련 표현이 확인된 비중복 문장을 문장별로 한 번씩 센다.",
    formula: "AI 관련 문장 수ᵢₜ = Σₛ 1(문장 s가 AI 관련 문장)",
    numerator: "AI 관련 문장 수",
    denominator: "해당 없음",
    unit: "개",
    sample: "2020–2025년 전체 기업-연도",
    missingZero: "자료가 없으면 결측이며, 적격 문장이 없으면 0이다.",
  },
  log1p_ai_sentence_count: {
    concept: "AI 관련 문장 수의 오른쪽 치우침을 완화한 변환값이다.",
    operation: "AI 관련 문장 수에 1을 더한 뒤 자연로그를 취한다.",
    formula: "로그 AI 관련 문장 수ᵢₜ = ln(1 + AI 관련 문장 수ᵢₜ)",
    numerator: "해당 없음",
    denominator: "해당 없음",
    unit: "자연로그값",
    sample: "AI 관련 문장 수가 관찰된 기업-연도",
    missingZero: "원변수가 결측이면 결측이며, 문장 수가 0이면 변환값은 0이다.",
  },
  whole_report_concreteness: {
    concept: "전체 보고서 어휘가 감각적으로 구체적인 정도를 요약한다.",
    operation: "유효 단어에 연결된 Brysbaert 구체성 점수의 평균을 계산한다.",
    formula: "전체 보고서 구체성ᵢₜ = Σ 구체성 점수(w) / 매칭 단어 수ᵢₜ",
    numerator: "매칭 단어의 구체성 점수 합",
    denominator: "구체성 점수가 연결된 유효 단어 수",
    unit: "Brysbaert 점수",
    sample: "유효 단어가 한 개 이상 매칭된 기업-연도",
    missingZero: "유효 분모가 없으면 결측이며 0으로 대체하지 않는다.",
  },
  ai_concreteness: {
    concept: "AI 관련 문장에 사용된 어휘의 구체성을 요약한다.",
    operation: "AI 관련 문장의 유효 단어에 연결된 Brysbaert 구체성 점수의 평균을 계산한다.",
    formula: "AI 관련 문장 구체성ᵢₜ = Σ AI 문장 구체성 점수(w) / AI 문장 매칭 단어 수ᵢₜ",
    numerator: "AI 관련 문장 매칭 단어의 구체성 점수 합",
    denominator: "AI 관련 문장에서 구체성 점수가 연결된 유효 단어 수",
    unit: "Brysbaert 점수",
    sample: "AI 관련 문장과 유효 매칭 단어가 있는 기업-연도",
    missingZero: "AI 관련 문장 또는 유효 분모가 없으면 결측이며 0으로 처리하지 않는다.",
  },
  past_tense_share: {
    concept: "분류 가능한 시제 표지 중 과거 시제 표지가 차지하는 비율이다.",
    operation: "spaCy의 문장분할·토큰화·품사 및 의존구문 분석 결과에 기존 규칙을 적용한다. VBD 태그의 동사를 과거 시제로 세어 과거·현재·미래 표지 수의 합으로 나눈다.",
    formula: "과거 시제 비율ᵢₜ = 과거 시제 수ᵢₜ / (과거 + 현재 + 미래 표지 수)ᵢₜ",
    numerator: "spaCy 품사 태그가 VBD인 동사 수",
    denominator: "VBD, VBP, VBZ 및 지정 미래 조동사 표지 수의 합",
    unit: "%",
    sample: "시제 표지 분모가 양수인 기업-연도",
    missingZero: "분모가 0이면 결측이며, 분모가 양수이고 과거 표지가 없으면 0이다.",
  },
  present_tense_share: {
    concept: "분류 가능한 시제 표지 중 현재 시제 표지가 차지하는 비율이다.",
    operation: "spaCy의 문장분할·토큰화·품사 및 의존구문 분석 결과에 기존 규칙을 적용한다. VBP 또는 VBZ 태그의 동사를 현재 시제로 세어 과거·현재·미래 표지 수의 합으로 나눈다.",
    formula: "현재 시제 비율ᵢₜ = 현재 시제 수ᵢₜ / (과거 + 현재 + 미래 표지 수)ᵢₜ",
    numerator: "spaCy 품사 태그가 VBP 또는 VBZ인 동사 수",
    denominator: "VBD, VBP, VBZ 및 지정 미래 조동사 표지 수의 합",
    unit: "%",
    sample: "시제 표지 분모가 양수인 기업-연도",
    missingZero: "분모가 0이면 결측이며, 분모가 양수이고 현재 표지가 없으면 0이다.",
  },
  future_tense_share: {
    concept: "분류 가능한 시제 표지 중 제한된 미래 조동사 표지가 차지하는 비율이다.",
    operation: "spaCy 분석에서 품사가 AUX인 will, shall, 'll, ’ll을 미래 조동사 표지로 세어 과거·현재·미래 표지 수의 합으로 나눈다. 미래지향성 전체를 측정하지 않는다.",
    formula: "미래 조동사 표지 비율ᵢₜ = 미래 조동사 표지 수ᵢₜ / (과거 + 현재 + 미래 표지 수)ᵢₜ",
    numerator: "품사가 AUX인 will, shall, 'll, ’ll의 수",
    denominator: "VBD, VBP, VBZ 및 지정 미래 조동사 표지 수의 합",
    unit: "%",
    sample: "시제 표지 분모가 양수인 기업-연도",
    missingZero: "분모가 0이면 결측이며, 분모가 양수이고 미래 표지가 없으면 0이다.",
  },
  lm_positive_share: {
    concept: "보고서 유효 어휘 중 Loughran–McDonald 긍정 범주 어휘의 비율이다.",
    operation: "긍정 범주와 일치한 단어 수를 전체 유효 보고서 단어 수로 나눈다.",
    formula: "긍정 어휘 비율ᵢₜ = 긍정 어휘 수ᵢₜ / 유효 보고서 단어 수ᵢₜ",
    numerator: "Loughran–McDonald 긍정 어휘 수",
    denominator: "전체 유효 보고서 단어 수",
    unit: "%",
    sample: "유효 보고서 단어 분모가 양수인 기업-연도",
    missingZero: "분모가 없으면 결측이며, 분모가 양수이고 일치 어휘가 없으면 0이다.",
  },
  lm_negative_share: {
    concept: "보고서 유효 어휘 중 Loughran–McDonald 부정 범주 어휘의 비율이다.",
    operation: "부정 범주와 일치한 단어 수를 전체 유효 보고서 단어 수로 나눈다.",
    formula: "부정 어휘 비율ᵢₜ = 부정 어휘 수ᵢₜ / 유효 보고서 단어 수ᵢₜ",
    numerator: "Loughran–McDonald 부정 어휘 수",
    denominator: "전체 유효 보고서 단어 수",
    unit: "%",
    sample: "유효 보고서 단어 분모가 양수인 기업-연도",
    missingZero: "분모가 없으면 결측이며, 분모가 양수이고 일치 어휘가 없으면 0이다.",
  },
  lm_uncertainty_share: {
    concept: "보고서 유효 어휘 중 Loughran–McDonald 불확실성 범주 어휘의 비율이다.",
    operation: "불확실성 범주와 일치한 단어 수를 전체 유효 보고서 단어 수로 나눈다.",
    formula: "불확실성 어휘 비율ᵢₜ = 불확실성 어휘 수ᵢₜ / 유효 보고서 단어 수ᵢₜ",
    numerator: "Loughran–McDonald 불확실성 어휘 수",
    denominator: "전체 유효 보고서 단어 수",
    unit: "%",
    sample: "유효 보고서 단어 분모가 양수인 기업-연도",
    missingZero: "분모가 없으면 결측이며, 분모가 양수이고 일치 어휘가 없으면 0이다.",
  },
  passive_voice_sentence_share: {
    concept: "행위의 대상이 문법적 주어로 나타나며, 행위자는 생략되거나 by 구문으로 표현될 수 있는 문장 구조의 비율이다.",
    operation: "spaCy 의존구문 분석에서 auxpass 또는 nsubjpass 관계가 하나 이상 확인된 문장을 수동태 문장으로 한 번 세어 전체 spaCy 문장 수로 나눈다.",
    formula: "수동태 문장 비율ᵢₜ = 수동태 판정 문장 수ᵢₜ / spaCy 문장 수ᵢₜ",
    numerator: "auxpass 또는 nsubjpass가 하나 이상인 문장 수",
    denominator: "spaCy가 분리한 전체 문장 수",
    unit: "%",
    sample: "분석 문장 분모가 양수인 기업-연도",
    missingZero: "분모가 0이면 결측이며, 분모가 양수이고 수동태 문장이 없으면 0이다.",
  },
  fog_index: {
    concept: "Fog Index는 문장 길이와 복합어 비율을 이용해 문서의 언어적 복잡성을 나타내는 지표이다.",
    operation: "문장당 단어 수와 전체 단어 중 복합어 비율을 결합한다.",
    formula: "Fogᵢₜ = 0.4 × [(단어 수ᵢₜ / 문장 수ᵢₜ) + 100 × (복합어 수ᵢₜ / 단어 수ᵢₜ)]",
    numerator: "유효 단어 수와 복합어 수",
    denominator: "유효 문장 수와 유효 단어 수",
    unit: "지수",
    sample: "유효 단어와 문장 분모가 모두 양수인 기업-연도",
    missingZero: "단어 또는 문장 분모가 0이면 결측이며, 복합어가 없으면 해당 비율은 0이다.",
  },
  report_word_count: {
    concept: "분석 대상 10-K 본문의 길이이다.",
    operation: "정제된 10-K 본문에서 유효 단어를 세어 계산한다.",
    formula: "보고서 단어 수ᵢₜ = Σₖ 1(단어 k가 유효 단어)",
    numerator: "유효 단어 수",
    denominator: "해당 없음",
    unit: "단어",
    sample: "2020–2025년 전체 기업-연도",
    missingZero: "본문 자료가 없으면 결측이며, 빈 본문이 명시된 경우에만 0이다.",
  },
  log_report_word_count: {
    concept: "보고서 길이의 오른쪽 치우침을 완화한 변환값이다.",
    operation: "보고서 단어 수에 자연로그를 취한다.",
    formula: "로그 보고서 단어 수ᵢₜ = ln(보고서 단어 수ᵢₜ)",
    numerator: "해당 없음",
    denominator: "해당 없음",
    unit: "자연로그값",
    sample: "보고서 단어 수가 양수인 기업-연도",
    missingZero: "단어 수가 결측 또는 0이면 결측이며 0으로 대체하지 않는다.",
  },
};

export const labelFor = (key) => VARIABLE_LABELS[key] || key;
export const unitFor = (key) => VARIABLE_UNITS[key] || "값";

export function formatVariableValue(value, key, digits = 2) {
  if (value === null || value === undefined || Number.isNaN(Number(value))) return "-";
  const number = Number(value);
  const unit = unitFor(key);
  if (unit === "%") return `${(number * 100).toFixed(digits)}%`;
  if (unit === "단어") return `${Math.round(number).toLocaleString("ko-KR")}단어`;
  if (unit === "개") return `${number.toLocaleString("ko-KR", { maximumFractionDigits: digits })}개`;
  if (unit === "점" || unit === "지수") return number.toLocaleString("ko-KR", { maximumFractionDigits: digits });
  return number.toLocaleString("ko-KR", { maximumFractionDigits: digits });
}
